### ISSUE TITLE
로고 만들었습니다

### ISSUE THREAD

**Issue by HyungJu** [deesle/deesle#1]
http://imgur.com/a/DaTVs

로고 입니당.. 
혹시 투명판 필요하시면 메시지주세요.. 
+) 혹시 opennamu 콜라보레이터 권한좀 주실래요? PR넣는게 쬐끔 귀찮아서요...

**Comment by BasixKOR** [comment]
감사합니다! 적용 고려해볼게요 :smile:
+) 전 사실상 오픈나무에서 손을 뗀 상태입니다.
