### ISSUE TITLE
일 한다면서요

### ISSUE THREAD

**Issue by surplus-dev** [deesle/deesle#10]
왜 안 하시죠

**Comment by BasixKOR** [comment]
안녕하세요, deesle입니다. 귀하의 연락에 깊은 감사를 드립니다. 현재 deesle의 모토는

> 느리고 정확하게

입니다. 이 때문에 개발이 늦춰지고 있지만, 높은 완성도로 유저분께 다가갈 수 있지 않을까 생각됩니다. 귀하의 관심과 사랑에 감사드리며, 해당 이슈를 닫겟습니다.

**Comment by surplus-dev** [comment]
느린데 정확하진 않은데 어떻게 된 일이죠 해명 좀

**Comment by BasixKOR** [comment]
안녕하세요. deesle 팀 담당자 베이직입니다. 사람이 실수 좀 할 수도 있는거죠 뭐... 넓은 마음으로 이해해주시길 바랍니다. 해당 이슈는 락 걸어놓겟습니다.

**Comment by BasixKOR** [comment]
제가 협박을 받은 관계로 락은 풀었습니다.
