### ISSUE TITLE
일 하시죠

### ISSUE THREAD

**Issue by 2DU** [deesle/deesle#6]
네

**Comment by BasixKOR** [comment]
해당 사항 반영하겟습니다.

**Comment by 2DU** [comment]
한다메요

**Comment by BasixKOR** [comment]
일 하고 있어요 푸시를 안할 뿐

2017년 1월 22일 (일) 오후 6:12, 2DU <notifications@github.com>님이 작성:

**Comment by BasixKOR** [comment]
제가 정말 모범적으로 아주 잘 일 하고 있기 때문에 닫겟습니다.

**Comment by 2DU** [comment]
푸시 하시죠

**Comment by BasixKOR** [comment]
Test 성공시까지는 푸시가 없을 것 같네요. 다른 부분도 작업하겟습니다 :)

**Comment by 2DU** [comment]
...
